import React from 'react';
import './Terms.scss';

export const Terms = () => {
    return (
        <div className="terms">
            <h1 className="terms-header">Beauty Shop - Terms & Regulations</h1>
            <p className="terms-regulations">1. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt dapibus ipsum, vitae cursus turpis dapibus nec. Ut id metus sed turpis porttitor vehicula. Praesent porta rutrum massa eget molestie. Ut vel pellentesque massa, ut blandit erat. Donec turpis nisi, posuere eu neque sit amet, eleifend accumsan arcu. Curabitur sollicitudin, libero at aliquet interdum, arcu purus congue leo, quis molestie metus eros sed dui. Donec interdum, lacus vitae viverra suscipit, est metus facilisis dui, porta tempor nibh risus sed lorem. Sed a leo tellus. Nunc vitae leo dictum, consectetur enim vel, sagittis lorem. Vivamus dictum libero metus.</p>

            <p className="terms-regulations">2. Etiam mattis, augue eu tempor vestibulum, augue sem suscipit sapien, in ultrices leo est et velit. Donec viverra convallis erat sed eleifend. Duis quis augue vitae justo molestie placerat nec vitae lectus. In sit amet metus felis. Praesent pellentesque iaculis est eu aliquam. Curabitur eu dui ac elit volutpat sodales ullamcorper in odio. Ut nunc quam, lacinia eget tristique a, commodo at tortor. Nunc facilisis diam eget tristique hendrerit. Praesent eu est eget massa convallis convallis nec quis mi. Donec id tristique nisi, et tincidunt velit. Aliquam sodales tempor porttitor. Nunc aliquet libero justo, eget sollicitudin ligula tempus quis. Maecenas gravida sit amet felis porttitor pharetra. Maecenas porta vestibulum erat sed laoreet. In sodales odio vitae metus semper lacinia.</p>

            <p className="terms-regulations">3. Maecenas nisi neque, luctus ut ligula vel, ullamcorper elementum metus. Mauris enim felis, imperdiet vel condimentum eu, suscipit aliquet diam. Fusce dui purus, rhoncus et metus vel, facilisis lobortis erat. Nam interdum ornare ipsum, a feugiat ex pharetra sit amet. Integer consectetur aliquet accumsan. Aliquam libero mi, auctor nec ornare in, varius ac quam. Ut pulvinar consectetur feugiat.Sed placerat diam a porta accumsan. Duis elementum, est vestibulum placerat tincidunt, velit erat pellentesque odio, ut euismod tortor odio sed justo. Integer efficitur, nulla vitae consectetur ullamcorper, nibh dui semper velit, et iaculis justo risus sit amet orci. Donec at est tempus nunc tempus feugiat eu nec dui. Sed finibus pulvinar iaculis. Donec viverra nulla est, eu convallis elit viverra id. Maecenas venenatis orci sit amet massa luctus, id egestas ligula porta. Maecenas in nisi leo. Sed eros ipsum, vehicula vel condimentum at, rhoncus in magna. Integer eget scelerisque lorem, eget posuere elit. Nam cursus justo eu elit volutpat, iaculis efficitur sapien sollicitudin. Proin pharetra finibus justo quis faucibus.</p>

            <p className="terms-regulations">4. Fusce vitae volutpat urna. Nullam ullamcorper suscipit tincidunt. Sed vitae tortor at enim rutrum mattis id non quam. Sed non placerat libero. Phasellus et efficitur neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras convallis est nec leo bibendum, eu venenatis purus rhoncus. Aenean consequat luctus mattis. Curabitur a vulputate nibh. Aenean enim justo, semper id tincidunt at, tristique luctus odio. Aenean ut diam sed urna sodales malesuada vel nec odio. Proin consectetur orci ac purus gravida, non ultricies justo maximus. Sed ut tellus in turpis interdum vehicula et ut odio. Aliquam pulvinar metus ac mauris pharetra, ut convallis quam porta. Vivamus odio dui, elementum eget erat quis, porttitor ullamcorper nibh. Nullam at orci quis diam sagittis maximus. Donec tempor bibendum felis eu faucibus. Nulla fermentum dolor ipsum, fringilla scelerisque ipsum mattis eu. Suspendisse non nisl nec mi mollis pretium ut sit amet tellus. Proin sed aliquam arcu, non pellentesque urna. Donec non dignissim lectus. Praesent efficitur elit libero, a dictum sem tempus non.</p>

            <p className="terms-regulations">5. Cras ornare gravida mauris, non consequat felis elementum sed. Maecenas vitae lorem eu lorem aliquam volutpat id in ipsum. Aenean tristique semper mollis. Pellentesque gravida enim in dolor varius, non dignissim arcu imperdiet. Nam molestie tortor at lorem ultricies, non placerat lacus lobortis. Etiam dignissim elementum fermentum. Donec sem diam, venenatis eu ipsum quis, pharetra gravida erat. Sed sed massa sapien. Vestibulum imperdiet pretium nulla, eu facilisis ligula rhoncus eu. Vivamus vitae fermentum magna, et convallis dui. Aliquam ut finibus tortor, et dictum ante. Nam porta tincidunt nibh, eget maximus dui. Morbi a leo pellentesque, scelerisque metus a, luctus sem. Quisque vitae posuere quam, at porttitor elit. Aenean dictum massa at tellus finibus, ut ultrices libero auctor. Fusce feugiat ultricies tincidunt. Cras non pharetra ante, eleifend condimentum ligula. Phasellus ultricies fermentum nisi, sit amet malesuada nulla ullamcorper ac. Curabitur tristique rhoncus tellus, non dapibus orci semper sed. Donec sed quam quis sapien suscipit fringilla. Mauris mollis orci et diam facilisis, nec dapibus odio fringilla. Nullam magna urna, placerat ornare condimentum ac, luctus non quam. Aenean sit amet felis dictum, commodo orci sit amet, sagittis tortor. Donec quis ullamcorper erat. Aliquam fermentum eu massa id porttitor.</p>

            <p className="terms-regulations">6. Pellentesque ac suscipit diam. Cras eget sagittis elit, suscipit sodales metus. In gravida placerat sapien non euismod. Nulla volutpat sit amet nisl vel porta. Duis ac eleifend velit. Donec vitae est pellentesque, mattis arcu vitae, pretium nulla. Sed eleifend sem vitae neque auctor, vel scelerisque leo venenatis. Maecenas eget arcu risus. Nullam porta ac magna vel maximus. Proin eget porttitor nibh. Sed a nibh placerat, condimentum justo eget, varius nunc. Nam dignissim, ex non tincidunt fringilla,mauris mi tempus nunc, vitae dignissim ante eros nec velit. Praesent ac leo sit amet dui fermentum blandit. Suspendisse ultrices ultrices nunc, a aliquam dui luctus in. Mauris convallis magna id metus aliquam, eget ornare orci vehicula. In sed tincidunt dolor.
            </p>
        </div>
    )
}

export default Terms;
